/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from "./routes/__root";
import { Route as LayoutRouteImport } from "./routes/_layout";
import { Route as LayoutAnalyticsRouteImport } from "./routes/_layout/analytics";
import { Route as LayoutAppAppIdRouteImport } from "./routes/_layout/app.$appId";
import { Route as LayoutCategoryCategoryIdRouteImport } from "./routes/_layout/category.$categoryId";
import { Route as LayoutDeveloperDeveloperIdRouteImport } from "./routes/_layout/developer.$developerId";
import { Route as LayoutIndexRouteImport } from "./routes/_layout/index";
import { Route as LayoutMyAppsRouteImport } from "./routes/_layout/my-apps";

const LayoutRoute = LayoutRouteImport.update({
	id: "/_layout",
	getParentRoute: () => rootRouteImport,
} as any);
const LayoutIndexRoute = LayoutIndexRouteImport.update({
	id: "/",
	path: "/",
	getParentRoute: () => LayoutRoute,
} as any);
const LayoutMyAppsRoute = LayoutMyAppsRouteImport.update({
	id: "/my-apps",
	path: "/my-apps",
	getParentRoute: () => LayoutRoute,
} as any);
const LayoutAnalyticsRoute = LayoutAnalyticsRouteImport.update({
	id: "/analytics",
	path: "/analytics",
	getParentRoute: () => LayoutRoute,
} as any);
const LayoutDeveloperDeveloperIdRoute =
	LayoutDeveloperDeveloperIdRouteImport.update({
		id: "/developer/$developerId",
		path: "/developer/$developerId",
		getParentRoute: () => LayoutRoute,
	} as any);
const LayoutCategoryCategoryIdRoute =
	LayoutCategoryCategoryIdRouteImport.update({
		id: "/category/$categoryId",
		path: "/category/$categoryId",
		getParentRoute: () => LayoutRoute,
	} as any);
const LayoutAppAppIdRoute = LayoutAppAppIdRouteImport.update({
	id: "/app/$appId",
	path: "/app/$appId",
	getParentRoute: () => LayoutRoute,
} as any);

export interface FileRoutesByFullPath {
	"/": typeof LayoutIndexRoute;
	"/analytics": typeof LayoutAnalyticsRoute;
	"/my-apps": typeof LayoutMyAppsRoute;
	"/app/$appId": typeof LayoutAppAppIdRoute;
	"/category/$categoryId": typeof LayoutCategoryCategoryIdRoute;
	"/developer/$developerId": typeof LayoutDeveloperDeveloperIdRoute;
}
export interface FileRoutesByTo {
	"/analytics": typeof LayoutAnalyticsRoute;
	"/my-apps": typeof LayoutMyAppsRoute;
	"/": typeof LayoutIndexRoute;
	"/app/$appId": typeof LayoutAppAppIdRoute;
	"/category/$categoryId": typeof LayoutCategoryCategoryIdRoute;
	"/developer/$developerId": typeof LayoutDeveloperDeveloperIdRoute;
}
export interface FileRoutesById {
	__root__: typeof rootRouteImport;
	"/_layout": typeof LayoutRouteWithChildren;
	"/_layout/analytics": typeof LayoutAnalyticsRoute;
	"/_layout/my-apps": typeof LayoutMyAppsRoute;
	"/_layout/": typeof LayoutIndexRoute;
	"/_layout/app/$appId": typeof LayoutAppAppIdRoute;
	"/_layout/category/$categoryId": typeof LayoutCategoryCategoryIdRoute;
	"/_layout/developer/$developerId": typeof LayoutDeveloperDeveloperIdRoute;
}
export interface FileRouteTypes {
	fileRoutesByFullPath: FileRoutesByFullPath;
	fullPaths:
		| "/"
		| "/analytics"
		| "/my-apps"
		| "/app/$appId"
		| "/category/$categoryId"
		| "/developer/$developerId";
	fileRoutesByTo: FileRoutesByTo;
	to:
		| "/analytics"
		| "/my-apps"
		| "/"
		| "/app/$appId"
		| "/category/$categoryId"
		| "/developer/$developerId";
	id:
		| "__root__"
		| "/_layout"
		| "/_layout/analytics"
		| "/_layout/my-apps"
		| "/_layout/"
		| "/_layout/app/$appId"
		| "/_layout/category/$categoryId"
		| "/_layout/developer/$developerId";
	fileRoutesById: FileRoutesById;
}
export interface RootRouteChildren {
	LayoutRoute: typeof LayoutRouteWithChildren;
}

declare module "@tanstack/react-router" {
	interface FileRoutesByPath {
		"/_layout": {
			id: "/_layout";
			path: "";
			fullPath: "/";
			preLoaderRoute: typeof LayoutRouteImport;
			parentRoute: typeof rootRouteImport;
		};
		"/_layout/": {
			id: "/_layout/";
			path: "/";
			fullPath: "/";
			preLoaderRoute: typeof LayoutIndexRouteImport;
			parentRoute: typeof LayoutRoute;
		};
		"/_layout/my-apps": {
			id: "/_layout/my-apps";
			path: "/my-apps";
			fullPath: "/my-apps";
			preLoaderRoute: typeof LayoutMyAppsRouteImport;
			parentRoute: typeof LayoutRoute;
		};
		"/_layout/analytics": {
			id: "/_layout/analytics";
			path: "/analytics";
			fullPath: "/analytics";
			preLoaderRoute: typeof LayoutAnalyticsRouteImport;
			parentRoute: typeof LayoutRoute;
		};
		"/_layout/developer/$developerId": {
			id: "/_layout/developer/$developerId";
			path: "/developer/$developerId";
			fullPath: "/developer/$developerId";
			preLoaderRoute: typeof LayoutDeveloperDeveloperIdRouteImport;
			parentRoute: typeof LayoutRoute;
		};
		"/_layout/category/$categoryId": {
			id: "/_layout/category/$categoryId";
			path: "/category/$categoryId";
			fullPath: "/category/$categoryId";
			preLoaderRoute: typeof LayoutCategoryCategoryIdRouteImport;
			parentRoute: typeof LayoutRoute;
		};
		"/_layout/app/$appId": {
			id: "/_layout/app/$appId";
			path: "/app/$appId";
			fullPath: "/app/$appId";
			preLoaderRoute: typeof LayoutAppAppIdRouteImport;
			parentRoute: typeof LayoutRoute;
		};
	}
}

interface LayoutRouteChildren {
	LayoutAnalyticsRoute: typeof LayoutAnalyticsRoute;
	LayoutMyAppsRoute: typeof LayoutMyAppsRoute;
	LayoutIndexRoute: typeof LayoutIndexRoute;
	LayoutAppAppIdRoute: typeof LayoutAppAppIdRoute;
	LayoutCategoryCategoryIdRoute: typeof LayoutCategoryCategoryIdRoute;
	LayoutDeveloperDeveloperIdRoute: typeof LayoutDeveloperDeveloperIdRoute;
}

const LayoutRouteChildren: LayoutRouteChildren = {
	LayoutAnalyticsRoute: LayoutAnalyticsRoute,
	LayoutMyAppsRoute: LayoutMyAppsRoute,
	LayoutIndexRoute: LayoutIndexRoute,
	LayoutAppAppIdRoute: LayoutAppAppIdRoute,
	LayoutCategoryCategoryIdRoute: LayoutCategoryCategoryIdRoute,
	LayoutDeveloperDeveloperIdRoute: LayoutDeveloperDeveloperIdRoute,
};

const LayoutRouteWithChildren =
	LayoutRoute._addFileChildren(LayoutRouteChildren);

const rootRouteChildren: RootRouteChildren = {
	LayoutRoute: LayoutRouteWithChildren,
};
export const routeTree = rootRouteImport
	._addFileChildren(rootRouteChildren)
	._addFileTypes<FileRouteTypes>();
